FluxML/model-zoo

char-rnn/char-rnn.jl
eta is an optional argument, not a kw argument
=> fix optimizer in char-rnn

mnist/vae.jl
(Approximately) reproduces the (binarized) MNIST example in [1]. Uses the same architecture as that proposed in the paper, but uses Adam rather than Adagrad, Xavier init. rather than sampling each parameter's initial value from a Gaussian with zero mean and variance of 0.01, and a broader prior on the model parameters.
I suspect my iterator implementation is unnecessary, so I would appreciate advice here if this is the case.
[1] - Kingma, Diederik P., and Max Welling. "Auto-encoding variational bayes." arXiv preprint arXiv:1312.6114 (2013).
=> VAE Implementation

mnist/autoencoder.jl
Using normal relu causes a small portion of the pixels in the reconstructed image to always be black.  It's a bit subtle with normal MNIST but becomes clear with other datasets like F-MNIST.  You can see this effect in the upper-left of the last four images below:
=> Switch autoencoder example to use leakyrelu

char-rnn/char-rnn.jl
Takes 5 minutes on a GPU, vs, 60 minutes on four CPUs. Both train the loss to about 80-85 and produce similar sample output.
=> char-rnn on gpu

README.md, other/bitstring-parity/Manifest.toml, other/diffeq/Manifest.toml, other/fizzbuzz/Manifest.toml, other/housing/Manifest.toml, other/housing/cuda/Manifest.toml, other/housing/cuda/Project.toml, other/housing/housing.jl, text/char-rnn/char-rnn.jl, text/char-rnn/cuda/Manifest.toml, text/char-rnn/cuda/Project.toml, text/phonemes/Manifest.toml, text/treebank/Manifest.toml, vision/cifar10/Manifest.toml, vision/cppn/Manifest.toml, vision/mnist/Manifest.toml, vision/mnist/conv.jl
This should make things much more robust to e.g. breaking CuArrays releases.
=> Update Flux version, add CUDA projects

README.md, other/iris/Manifest.toml, other/iris/Project.toml, other/iris/README.md, other/iris/iris.jl
This is a super simple model aimed at helping beginners get started with Flux.
It depends on an 'iris' Data module in Flux, PR here: https://github.com/FluxML/Flux.jl/pull/652.
If it doesn't make sense to have the iris Data module in Flux I can move that over here.
Please make any suggestions/changes you think might be appropriate.  Thank you!
=> Add logistic regression example on iris dataset.

tutorials/60-minute-blitz.jl
Changing `x` type from default `Float64` to `Float32`, to match `Dense` on comparison:
```julia
m = Dense(10, 5)
x = rand(Float32, 10)
m(x)
#-
m(x) == m.W * x .+ m.b
```
=> Fix x type to match m

vision/mnist/conv.jl
This change fixes an error I got and which seems to be due to the multiplication with 0.1 (Float64) converting the array to Array{Float64}
=> Do not let Float64 creep into the loss function

games/differentiable-programming/cartpole/DQN.jl, games/differentiable-programming/cartpole/DiffRL.jl, games/differentiable-programming/cartpole/Manifest.toml, vision/mnist/conv.jl
The DQN example which uses the CartPole environment has been updated to stop converting the actions (`Discrete(2)`) to `{-1, 1}`. Please refer to this [PR](https://github.com/FluxML/Gym.jl/pull/29) for more details.
=> Updated DQN CartPole example to utilise Gym's Space types

vision/mnist/vae.jl
As mentioned by @AbinavRavi in KL-divergence equation we should have 2*logσ instead of logσ.^2 but the other mistake is the sign of this which should be -2*logσ
=> Another mistake in KL-divergence equation vae.jl

text/lang-detection/Manifest.toml, text/lang-detection/Project.toml, text/lang-detection/README.md, text/lang-detection/model.jl, text/lang-detection/scrape.jl
With Cascadia.jl updated, **model-zoo/text/lang-detection** has been updated.
`AbstractTrees.jl` dependency for scrape.jl has been dropped, although required due to Gumbo.jl. 
Dependencies added: `Random` is required for _shuffle_ and `Unicode` for _string normalization_. 
Also, the 2 spaced/tab indentation has been changed to 4 spaces.
The remaining deprecations have been fixed and **the code works on Julia 1.0.3** 
I have uploaded the [demo notebooks on a separate branch](https://github.com/Ayushk4/model-zoo/tree/demo/text/lang-detection) named as _scrape.ipynb_ and _model.ipynb_.
I will push manifest.toml and project.toml soon.
Please suggest changes if any.
=> Fix the deprecated Language-Detection Model

README.md
The path to place the datasets for use with MetalHead is not clear. This PR aims to add a note entry in `README.md` to specify where to place the datasets. Useful for first time users
=> Added note for usage of common datasets

text/char-rnn/char-rnn.jl
The method `truncate!` is no longer used and `reset!` is now preferred. Changing it so that this example runs without errors.
=> change `truncate!` to `reset!` in char-rnn

README.md
The "game" directory has been moved into the contrib directory and hence the url in README needs an update.
=> Fix the hyperlink for the games dir in README

tutorials/60-minute-blitz.jl, tutorials/Manifest.toml, tutorials/Project.toml
Removed dependency on CuArrays as it was causing conflicts with Flux and erroring. Described more in #252.  
Updated description to refer to CUDA.
Eliminated `using Zygote` as it's not needed explicitly at any point for Flux to train the model.
=> Updated to CUDA from CuArrays dependency

vision/mnist/mlp.jl
In example of [MNIST mlp](https://github.com/FluxML/model-zoo/blob/0e8de61cf466868b13a629e9a9275cfe7eafa6c6/vision/mnist/mlp.jl#L21),
original data is always downloaded even if it is already in the local machine.
This pull request fixes this issue while bypassing the confirmation under the guidance [here](https://www.oxinabox.net/DataDeps.jl/stable/z10-for-end-users/#Configuration-1).
=> Avoid repeating download

vision/cdcgan_mnist/Manifest.toml, vision/dcgan_mnist/Manifest.toml, vision/dcgan_mnist/Project.toml, vision/dcgan_mnist/dcgan_mnist.jl
Fixes:
- Replace Flux.logitbinarycrossentropy with Flux.Losses.logitbinarycrossentropy
- Take the latent_dim as input to the generator constructor
No yet fixed:
- Crashes, likely because of this issue : https://github.com/FluxML/Flux.jl/issues/1350
see https://github.com/FluxML/model-zoo/issues/266
=> Fix dcgan_mnist model

vision/cifar10/Manifest.toml, vision/cifar10/Project.toml, vision/cifar10/cifar10.jl
- Replaces dependencies which prevented updating to flux 0.11.4
- Wrote custom training loop to allow data to be moved to the GPU in batches, this allows running the model on lower end cards without OOM errors.
=> Fix cifar10 model

vision/lenet_mnist/Manifest.toml, vision/lenet_mnist/Project.toml, vision/lenet_mnist/lenet_mnist.jl
- Replace CUDAapi with CUDA
- Workaround to fix saving the model on julia 1.6-beta1 (https://github.com/JuliaIO/BSON.jl/issues/80)
Some small less urgent changes which I now see I added to the commits:
- Removes some unused dependencies from Project.toml
- Parameters.@with_kw replaced with Base.@kwdef
see https://github.com/FluxML/model-zoo/issues/266
=> Fix lenet_mnist model

text/treebank/Manifest.toml, text/treebank/Project.toml, text/treebank/data.jl, text/treebank/recursive.jl
Several errors in the sscript prevented it from running. Script runs fine now and loss seems to converge, but not 100% sure if the model is now how it was supposed to be..
=> Fix treebank model

tutorials/transfer_learning/transfer_learning.jl
The transfer learning tutorial sometimes returns NaNs (see https://github.com/FluxML/model-zoo/issues/242). Removing the softmax layer and training with a logitcrossentropy loss seem to solve these cases.
=> Fix NaNs in some cases for transfer learning tutorial

vision/vae_mnist/vae_plot.jl
In vae_plot.jl the sigmoid needs to be applied to the sampled output from the decoder. Otherwise, the generated image `output/manifold.png` is corrupted.
The error was caused by the commits in FluxML#267 that removed the sigmoid from the last decoder layer to enable the use of the more numerically stable logitbinarycrossentropy loss. However, only the output in [vae_mnist.jl](https://github.com/FluxML/model-zoo/blob/7436c5c7457fd5aaa5ddeec09f506fec42d43639/vision/vae_mnist/vae_mnist.jl#L160) was adapted. The output in `vae_plot.jl` was not adapted.
=> fix grey image output in vae_mnist

contrib/games/differentiable-programming/cartpole/DQN.jl, vision/conv_mnist/conv_mnist.jl
`WeightDecay` and similia should always be applied before the actual optimizer, otherwise their contribution to the gradient won't be multiplied by the learning rate.
cc @carlobaldassi
=> fix use of decays

contrib/games/differentiable-programming/cartpole/DQN.jl
Revert part of the change in #303 since applying InvDecay as last makes more sense (at odds with WeightDecays that has to be always first). This way InvDecay acts as a learning rate scheduler.
=> revert InvDecay swap

text/char-rnn/char-rnn.jl
Fixed a small issue that came up [here](https://discourse.julialang.org/t/issues-with-recurrent-layers-in-flux-jl/67815/9) on discourse about using dot notation over RNN models. Switched to use list comprehension to make sure the evaluation order is correct.
=> switch dot/map to list comprehension for RNN eval

text/char-rnn/char-rnn.jl
Right now, I get the following when trying to run char-rnn.jl: 
```Julia
ERROR: LoadError: error in method definition: function StatsBase.sample must be explicitly imported to be extended
Stacktrace:
[1] top-level scope
```
Updating the function name resolves this issue.
=> Fix error when running char-rnn.jl

README.md
The particular docs section has been moved to somewhere else. Fixed it!
=> Fix a dead link in README

vision/conv_mnist/conv_mnist.jl
PR removes the duplication of the incomplete get_data() function on line 116 and updates the usage of MLDatasets for v0.6+ as in #353.
=> Delete get_data() duplication in conv_mnist.jl

README.md
I checked the project (or manifest) files for the version of Flux on which these models were run. Maybe useful to have up front?
I guess it's an admission that they aren't all going to stay perfectly current. Better to be honest though.
Also adds entries for a few recent PRs which were missing from the Readme's list.
=> Add versions to Readme list

README.md
Should this package's readme list examples which aren't hosted here, which might be of interest? Seems like a somewhat natural place to look. 
This thread points to MLJFlux:
https://discourse.julialang.org/t/flux-categorical-arrays-roc-curves-confusion-matrices/91282/10
=> Link to MLJFlux examples?

README.md, vision/dcgan_mnist/Manifest.toml, vision/dcgan_mnist/Project.toml, vision/dcgan_mnist/dcgan_mnist.jl
Last I upgraded a few models to use explicit-mode gradients, Flux 0.13.9. 
They do run, but I did not check with a GPU, nor run them for the full number of epochs.
In several of these, I also
* Removed Parameters.jl, this seems weird as it's built-in, and the whole make-a-struct-for-parameters style here seems over-engineered already. 
* Removed elaborate code for defining `device = gpu` etc. Isn't the point of `gpu` that it warns you then does nothing, if used without a GPU?
(Separate commits, to be easy to remove if people have strong feelings.)
=> Explicit dcgan mnist

README.md, text/char-rnn/Project.toml, text/char-rnn/README.md, text/char-rnn/char-rnn.jl
This resolves #379. The `char-rnn.jl` example was broken after Flux `v0.13.9` due to a data format issue.
This PR does a few things:
- fixes #379 
- adds gpu support
- adds better train/test split
- simplifies data preparation
- adds averaged loss metric
- minor formatting changes
- removes callback (in favor of per-epoch loss report)
=> Update char-rnn.jl for `v0.13.9` and some improvements

README.md, vision/mlp_mnist/Manifest.toml, vision/mlp_mnist/Project.toml, vision/mlp_mnist/mlp_mnist.jl
Fixes #384 and updates `mlp_mnist` to use explicit gradients (compat updated to use `Flux = 0.13.9` and `MLDatasets = 0.7`
=> Fix mlp mnist explicit gradients

README.md, vision/conv_mnist/Manifest.toml, vision/conv_mnist/Project.toml, vision/conv_mnist/conv_mnist.jl
There's a lot of junk in these files. Perhaps we should clean them up.
Text can go in README. Code should encourage interactive use, and hence avoid big functions called exactly once. No more parameter structs. 
Readable version, since the diff is huge:  https://github.com/FluxML/model-zoo/blob/simpler_lenet/vision/conv_mnist/conv_mnist.jl
~~WIP, would like https://github.com/FluxML/Flux.jl/pull/2186 and https://github.com/JuliaML/MLUtils.jl/issues/144 .~~ Edit: or just https://github.com/FluxML/Flux.jl/pull/2240 now.
=> Simplify LeNet

vision/mlp_mnist/Manifest.toml, vision/mlp_mnist/Project.toml, vision/mlp_mnist/README.md, vision/mlp_mnist/mlp_mnist.jl
Same idea as https://github.com/FluxML/model-zoo/pull/394, to remove all this baroque junk of making structs you use once, and functions you call once, to just focus on the essentials. But even simpler than #394, no GPU, no NamedTuples, no saving. 
* Before: https://github.com/FluxML/model-zoo/blob/master/vision/mlp_mnist/mlp_mnist.jl
* After: https://github.com/FluxML/model-zoo/blob/simpler_mlp/vision/mlp_mnist/mlp_mnist.jl
~~Maybe some of the text in the old one should move to the readme.~~
=> Simpler MLP

other/autoregressive-process/Project.toml, other/fizzbuzz/Project.toml, other/iris/Project.toml, text/char-rnn/Project.toml, text/lang-detection/Project.toml, tutorials/transfer_learning/Project.toml, tutorials/transfer_learning/transfer_learning.jl, vision/dcgan_mnist/Project.toml, vision/mlp_mnist/Project.toml, vision/spatial_transformer/Project.toml, vision/vae_mnist/Project.toml, vision/vgg_cifar10/Project.toml
This updates Project.toml to allow 0.14, but without updating all the manifests.
=> Allow Flux 0.14 everywhere 0.13 was used

text/char-rnn/Manifest.toml, text/char-rnn/Project.toml, text/char-rnn/char-rnn.jl
Fixed issue #398. 
* Changed file `char-rnn.jl` according to description/sugesstion in issue text.
* Set Julia version to 1.10. The Julia 1.10 runtime was not able to run the 1.6 version.
=> PR for issue #398.
