FluxML/model-zoo

- mnist/autoencoder.jl
address: https://github.com/FluxML/model-zoo/pull/9#discussion_r160960134
> mnist/autoencoder: add more comment about single encoder/decoder

- mnist/conv.jl
Conv2d -> Conv
maxpool2d -> maxpool
> Updated deprecated function calls

- bitstring-parity/README.md
- bitstring-parity/data.jl
- bitstring-parity/xor1.jl
- bitstring-parity/xor2.jl
- bitstring-parity/xor3.jl
Hey, did this for fun in an effort learn Flux, super cool how straightforward it is to use RNNs with variable length strings.
Basically took the lang-detection model and tweaked it a bit so I understand if you don't wanna merge this.
> Parity of bit strings

- other/housing/housing.jl
The update should compensate for differences.
---
```julia
update!(x, g[x]*η)
loss(x, y) = 952.6895439667812 (tracked)
loss(x, y) = 1914.1929994135733 (tracked)
loss(x, y) = 5464.468001845795 (tracked)
loss(x, y) = 21266.960471735136 (tracked)
loss(x, y) = 96817.92559775215 (tracked)
loss(x, y) = 466399.6937162529 (tracked)
loss(x, y) = 2.2868664665712295e6 (tracked)
loss(x, y) = 1.1272387463227632e7 (tracked)
loss(x, y) = 5.565014401890722e7 (tracked)
loss(x, y) = 2.7486217658737e8 (tracked)
Tracked 1-element Array{Float64,1}:
-458.224517605224
```
---
```julia
update!(x, -g[x]*η)
loss(x, y) = 27.37267773987512 (tracked)
loss(x, y) = 25.879787090443752 (tracked)
loss(x, y) = 24.89573542272762 (tracked)
loss(x, y) = 24.239304354868356 (tracked)
loss(x, y) = 23.794431155858636 (tracked) …
```
> Update housing.jl (update should compensate for differences)

- README.md
- other/diffeq/Manifest.toml
- other/diffeq/Project.toml
- other/diffeq/diffeq.jl
Mixed-mode AD through a Lotka Volterra simulation. Generates a nice animated plot!
> DiffEq example

- vision/mnist/vae.jl
Changed the KL-divergence formula from log(sigma).^2 to 2*log(sigma)
> Changed the KL-Divergence formula in vae.jl #73

- other/diffeq/dde.jl
- other/diffeq/sde.jl
> fix DDE/SDE naming

- other/housing/cuda/Manifest.toml
- text/char-rnn/cuda/Manifest.toml
- vision/mnist/cuda/Manifest.toml
> Updated cuda manifests

- other/diffeq/Manifest.toml
- other/diffeq/README.md
- other/diffeq/neural_sde.jl
Currently it StackOverflows in backprop every once in awhile
> Add neural SDE example

- audio/speech-blstm/00-data.jl
- audio/speech-blstm/01-speech-blstm.jl
- audio/speech-blstm/Manifest.toml
- audio/speech-blstm/Project.toml
- audio/speech-blstm/README.md
- audio/speech-blstm/TIMIT/README.md
- audio/speech-blstm/test/README.md
- audio/speech-blstm/train/README.md
This is a submission of one of the neural networks I worked on, and the one that actually showed some reasonable level of performance if trained long enough. It does not use the fancy CTC loss function, but it outperforms any of the CTC ones that I've attempted.
> Add framewise speech recognition network

- tutorials/60-minute-blitz.jl
concatentaing -> concatenating
> Fixed typo

- text/char-rnn/char-rnn.jl
> Removing unused keyword arg in char RNN example

- .gitlab-ci.yml
- script/Manifest.toml
- script/Project.toml
Useful to get model zoo runs on the GPU with GitLab. Steps in the direction to be able to trigger runs using a comment on Flux.jl to build specified models
cc @maleadt
> Add GitLab config to get bot up

- vision/mnist/autoencoder.jl
Accessing data field of sample "after" image caused error
> Fix mnist/autoencoder bug

- tutorials/60-minute-blitz.jl
Flux Tracker functions like back!() and grad() removed in favor of new Zygote's gradient().
Training Loop updated using new Flux.Optimise.update!()
> Update 60-minute-blitz tutorial

- contrib/games/differentiable-programming/trebuchet/DiffRL.jl
With these changes and changes in Gym proposed in https://github.com/FluxML/Gym.jl/pull/42 I am able to run the DiffRL.jl example
> Updates for Flux 0.10

- .gitpod.Dockerfile
- .gitpod.yml
Hello! :smile:
I saw you had a Gitpod config and also that Julia wasn't properly installed so I created this PR with Julia properly configured!
> Update Gitpod Config to properly configure Julia

- text/char-rnn/char-rnn.jl
Adding an optional seed to give context to the text generation step.
> Adding a seed for sampling

- vision/cdcgan_mnist/.gitignore
- vision/mnist/Manifest.toml
- vision/mnist/Project.toml
- vision/mnist/mlp.jl
@DhairyaLGandhi 
I didn't include the Manifest in my recent merge request, and I had a line to download the dataset in the global scope. I moved it into the `getdata` function. 
I also must have not pushed the Project.toml last time? 
This PR fixes those 3 mistakes.
Also, generally, is it preferred to make small changes 1 at a time, or just merge things as they become ready?
> Upload manifest, include download in the getdata function

- other/housing/Manifest.toml
- other/housing/Project.toml
- other/housing/housing.jl
This model had a diverging loss due to a minus sign in the update step. This PR does also replace the custom meansquareerror function with `Flux.Losses.mse`.
> Fix housing model

- other/bitstring-parity/Manifest.toml
- other/bitstring-parity/Project.toml
- other/fizzbuzz/Manifest.toml
- other/fizzbuzz/Project.toml
- other/iris/Manifest.toml
- other/iris/Project.toml
- text/char-rnn/Manifest.toml
- text/char-rnn/Project.toml
- text/lang-detection/Manifest.toml
- text/lang-detection/Project.toml
- text/phonemes/Manifest.toml
- text/phonemes/Project.toml
- vision/cdcgan_mnist/Manifest.toml
- vision/cdcgan_mnist/Project.toml
- vision/cifar10/Manifest.toml
- vision/cifar10/Project.toml
- vision/cppn/Manifest.toml
- vision/cppn/Project.toml
- vision/dcgan_mnist/Manifest.toml
- vision/dcgan_mnist/Project.toml
- vision/mnist/Manifest.toml
- vision/mnist/Project.toml
Adds a [compat] section to the Project.toml files for the models. The models are tested to work without errors on these versions.
> Add compats

- vision/cifar10/cifar10.jl
I apparently forget to commit these lines. If not included the script complains about the missing device function This is not the nicest solution but it does at least fix the script.
> Missing commit to fix cifar10 example

- vision/mnist/Manifest.toml
- vision/mnist/Project.toml
Without this, the autoencoder example fails on the last line.
> Add ImageIO dependency required for autoencoder example

- tutorials/60-minute-blitz/60-minute-blitz.jl
Improved the explanation for the Momentum algorithm, fixed typos and removed a redundant variable initialization in the code.
> Improved explanation, removed redundant variable and fixed typos in the Blitz tutorial

- README.md
limit boilerplate code to the minimum, with short and clean code
> Recommend that contributions be short and sweet

- tutorials/60-minute-blitz/60-minute-blitz.jl
Changed dims in `permutedims` from `HWCN` to `WHCN`.
> Corrected image dims from HWCN to WHCN

- vision/dcgan_mnist/dcgan_mnist.jl
As weight initialization is also a part of DCGAN paper, I thought I'd add it to the code :)) #309
> Added weight initialization in DCGAN

- text/char-rnn/char-rnn.jl
In the char-rnn example, the LSTM states were not reset between minibatches or epochs (but only one epoch was used, so this wasn't a real problem).
This PR redefines the loss to properly reset the model between minibatches. It also adds epochs (defaulted to 2 for now, not sure what others think should be the value. maybe 20?) to the training args.
> Reset state and add epochs in Char RNN example

- tutorials/dataloader/README.md
> A hotbath is nice but here a hotbatch is needed

- tutorials/transfer_learning/dataloader.jl
I am working on a Transfer Learning Tutorials and was using this code so I decided to port over my comments which will hopefully help make this more accessible
> Update dataloader.jl with comments

- README.md
Adding a small text with some guidelines on how to add documentation to existing models.
> Add suggestion for contributing with documentation

- text/treebank/README.md
- text/treebank/data.jl
- text/treebank/recursive.jl
Reference Issue [340](https://github.com/FluxML/model-zoo/issues/340). 
Following some of the comments, this example contains fewer explanations and instead references the original paper that explains in detail how to model works.
> Add README and literature background to treebank

- README.md
- vision/spatial_transformer/Manifest.toml
- vision/spatial_transformer/Project.toml
- vision/spatial_transformer/spatial_transformer.jl
This previously didn't have a manifest
> Explicit spatial transformer

- README.md
- vision/vgg_cifar10/Manifest.toml
- vision/vgg_cifar10/Project.toml
- vision/vgg_cifar10/vgg_cifar10.jl
> Explicit vgg cifar10

- README.md
- text/char-rnn/Manifest.toml
- text/char-rnn/Project.toml
- text/char-rnn/char-rnn.jl
One more upgrade to explicit / structural gradient. Builds on #380.
~~This wants  https://github.com/JuliaDiff/ChainRules.jl/pull/687 hence draft~~ done.
> Explicit char rnn

- text/lang-detection/README.md
- text/lang-detection/model.jl
Reference issue [#340](https://github.com/FluxML/model-zoo/issues/340)
> Add literature background to character-level language detection

- README.md
- tutorials/transfer_learning/Manifest.toml
- tutorials/transfer_learning/Project.toml
- tutorials/transfer_learning/dataloader.jl
- tutorials/transfer_learning/transfer_learning.jl
I updated the transfer learning tutorial for current Flux.
> Update transfer learning tutorial

- README.md
[Please delete this text and describe your change here.
For bugfixes, please detail the bug and include a test case which your patch fixes.
If you are adding a new feature, please clearly describe the design, its rationale, the possible alternatives considered.
It is easiest to merge new features when there is clear precedent in other systems; we need to know we're taking
the right direction since it can be hard to change later.]
> Fixed the tutorials link to the correct page in ReadMe

- README.md
- vision/conv_mnist/Manifest.toml
- vision/conv_mnist/Project.toml
- vision/conv_mnist/conv_mnist.jl
Closes #400, and does #399 for this model
> cov_mnist: fix a bracket, update to 0.14

- vision/mlp_mnist/README.md
> fix typo in mnist readme
